
// English detailed meanings for numbers

export const enDetailedMeanings = {
  3: "This name number denotes hard work, intelligence, success and a comfortable life. They will be highly educated and will gradually progress in life.",
  4: "As this name number will be only for very short names, it signifies a person or a thing that is popular. It does not bring luck as one might deserve. They will have needless fears, sickness and opposition. They can be well informed and worldlywise, but still they would work only as subordinates to others",
  5: "This number gives the power to charm people, exude dynamism and to lead a luxurious life enjoying fame and prominence. They spend money lavishly. These people should cultivate perseverance and concentration of mind.",
  6: "This number signifies a peaceful life, a satisfied and contented mind and a good standard of living. Being a single digit, it does not have much power.",
  7: "This name number represents high principles and virtuous qualities, which may flourish with divine grace. Unexpected changes will take place. Efforts will not produce the desired results.",
  8: "This Name number gives you great success in spiritual life. If they have no control over pleasures, success will be delayed. After a big struggle they may succeed. They will have to face unexpected dangers and difficult circumstances in life.",
  9: "If the name comes under this number, it signifies wisdom and capability. It also denotes travel, struggles against odd situations and victory in the end. When they finally succeed, they will have a long life of luxury.",
  10: "This number when comes as a name indicates the sound or resonance of the primal force. This is depicted in the ancient texts as a snake enmeshed within a wheel. Those named under this number will be dignified and popular. Confidence and patience coexist in their lives but their fortunes will change frequently. It is like a revolving wheel, with ups and downs frequently. They must be honest in all their activities and they are bound to gain popularity. They will lead happy lives since there will be no paucity of funds.",
  11: "Those having 11 as their name number will come up in life by their sheer faith in God. They will profit by various means very easily. They may be riddled with unforeseen problems and dangers, as if to test their faith. Sometimes, they tend to meddle with matters that do not concern them. They are liable to be let down by their family and friends. If they have faith in God, they will definitely attain great heights in life. If they lack faith, they are bound to face a lot of dangers.",
  12: "These people naturally possess the ability to attract people by their power of speech. They sacrifice their lives for the welfare and happiness of others by shouldering their burdens too.",
  13: "People in the western counties regard this number as unlucky and ominous. They do not stay in rooms or houses having this number and some hotels even do not have rooms with this number. Unexpected events of sorrowful nature occur frequently. Men of this number have bitter experiences and face a lot of difficulties because of women. Though these people do manage to come up in life materially, they would still lead lives full of struggles. This is not a desirable name number. This number gives only severe grief, if birth and destiny numbers are also unlucky.",
  14: "This number is suitable for trade. Those having this Name number are always surrounded by a lot of people and things. They are successful in various trades and will meet a lot of friends. They may have strange problems and may face disappointments by trusting others. They may also face risk from thunder, lightning, water and fire. They undertake frequent travels. These people are advised to be careful while travelling in fast-moving vehicles. If the product in which they trade also comes under number 14, it will have excellent public patronage. The matters concerning love and marriage must be considered and reconsidered many times before a decision is taken. If not, these people may marry in haste and repent at leisure. This number can be called a very lucky number.",
  15: "The determination to succeed in all the plans and earn money and the quest for achieving one's ends are signified by this number. Lust, revenge and malice may push the people of this Name number to a vile state of mind. They may become selfish gradually. A charming appearance and forceful speech will help them in achieving their interests. Though this name number is not one conducive to leading a virtuous life, it is one that is ideally suited for purely material success. An alluring personality, excellence in fine arts and a witty nature yield positive results in any activity that can generate huge profits. Many people come forward to help them in need. Life will be luxurious. If their birth number is also favourable, these people will attain fame, wealth and distinction in all aspects of life",
  16: "This number signifies speedy progress and a sudden downfall. Ancient texts depict this number by a picture showing the shattering of a tall tower and a king's head with his crown falling from its top. This truth was proved when Japan (16) fell prey to the nuclear bombs. The Japanese Emperor was considered to be God-incarnate and his people would not even look at him from an elevated place. Unfortunately, the Americans bombed Japan stripping the Emperor of his status and the consequences are well known even today. If your name number is 16, it is better to change it to some other lucky number. This number induces new imaginative thoughts which will be reflected in the writings of the person.",
  17: "This name number gives demonic qualities while pursuing the goals. It brings many problems and trials. However, they will persistently struggle without giving up. Failures will prompt them to struggle more actively. In the end they will be successful, and they get permanent prosperity and great fame. Some of them risk their lives to attain their goals and so achieve progress. The world can never forget them. This number can give mystic powers also.",
  18: "This name number, which signifies the decline of divinity, will bring in problems, procrastination in all matters, deviousness, and dangerous enemies. Their selfishness may induce them to indulge in antisocial activities. They follow evil ways consciously and become highly selfish. Life devoid of peace and rest will be the order of the day. This number signifies growth of personal desires at the cost of virtue. Desires will come to an end. Divine grace will get destroyed. (Hindu Epics record that Mahabharat war was fought for 18 days and 18 divisions fought the war in which the Pandavas had to kill their own elders and gurus in the battle. Although considered holy by the Hindus, it is the eighteen-chaptered Bhagavat Gita that spurred Arjuna into the war). This number, which denotes jealousy, malice and dangers due to fire and weapons, is not considered desirable.",
  19: "Ancient books on this subject attribute mastery over the Three Worlds to this Number and as such, these people will be the focus of attention wherever they are. This number indicates the Rising Sun. This also has been described as the \"Prince of the Celestial World\" in ancient Indian texts and as an \"Ideal Lover\" in Egyptian scriptures. The sun becomes brighter as the day lengthens and so also these people progress as their age advances. Position, status, happiness, success and wealth will be gradually on the rise. Being well-disciplined, they will look young and will be very active even in their advanced age. They must be honest even in matters related to sensual pleasures.",
  20: "This spiritual number represents a drumbeat heralding triumph or victory. People having this Name number work for liberation and social reforms. They are capable of providing relief to the masses from grief and struggles. The world will admire them. When they work with personal motives, they are extremely selfish and highly destructive. The 20 number people will excel in medical practice using toxic medicines and deal with poisonous drugs. These people possess the ability to awaken the sleeping masses and lead them to very great achievements. When they go out of their way to satisfy their selfish needs, delay and utter failure will be imminent. (HITLER, born on the 20th, spurred Germany into war and faced a humiliating defeat. He is a very good example of this Name number. He was represented by the battle drum that goaded the people to follow a selfish motive which led to destruction)",
  21: "These people are self-centered and concerned about their own happiness and matters profitable to them. With great determination, they rise steadily in life and reach the pinnacle of success. Their tactful behaviour helps them to solve all their problems. They struggle hard in their early days but achieve success and happiness as they grow up. They will attain and retain good positions permanently in their lives.",
  22: "The characteristics of those born on the 22nd hold equally good for this Name number also. This number instigates base feelings and emotions. They are drawn towards gambling, drinking, speculation and other vices and will readily indulge in them. They may move towards self-destruction at a great speed and are generally surrounded by wicked and fraudulent people. They invariably earn a bad reputation. They dislike the counsel of others. If the influence of their date of birth is favourable, they can be successful. Otherwise, they have to struggle to prevent total failure. Those with selfish motives invariably urge these people to devious ways in order to further their own interests. They are good administrators and can meet any problem or difficulty with courage. Dangerous circumstances are foreseen. They often face humiliations."
  // Add more descriptions as needed
};
