
// Vietnamese detailed meanings for numbers

export const viDetailedMeanings = {
  3: "Số tên này biểu thị sự chăm chỉ, thông minh, thành công và cuộc sống thoải mái. Họ sẽ được giáo dục cao và sẽ dần tiến bộ trong cuộc sống.",
  4: "Vì số tên này chỉ dành cho những tên rất ngắn, nó biểu thị một người hoặc một thứ phổ biến. Nó không mang lại may mắn như người ta mong muốn. Họ sẽ có những nỗi sợ hãi không cần thiết, bệnh tật và đối lập. Họ có thể được thông báo tốt và hiểu biết về thế giới, nhưng họ vẫn chỉ làm việc như cấp dưới của người khác",
  5: "Số này mang lại sức mạnh để quyến rũ mọi người, tỏa ra sự năng động và dẫn đến một cuộc sống xa hoa tận hưởng danh tiếng và nổi bật. Họ tiêu tiền một cách hoang phí. Những người này nên trau dồi tính kiên trì và tập trung tâm trí.",
  6: "Số này biểu thị một cuộc sống bình yên, một tâm trí hài lòng và một tiêu chuẩn sống tốt. Vì là một chữ số đơn, nó không có nhiều sức mạnh.",
  7: "Số tên này đại diện cho các nguyên tắc cao và phẩm chất đạo đức, có thể phát triển mạnh với ân sủng thiêng liêng. Những thay đổi bất ngờ sẽ diễn ra. Nỗ lực sẽ không mang lại kết quả mong muốn.",
  8: "Số tên này mang lại cho bạn thành công lớn trong đời sống tâm linh. Nếu họ không kiểm soát được niềm vui, thành công sẽ bị trì hoãn. Sau một cuộc đấu tranh lớn, họ có thể thành công. Họ sẽ phải đối mặt với những nguy hiểm bất ngờ và những hoàn cảnh khó khăn trong cuộc sống.",
  9: "Nếu tên thuộc số này, nó biểu thị sự khôn ngoan và khả năng. Nó cũng biểu thị du lịch, đấu tranh chống lại những tình huống khó khăn và chiến thắng cuối cùng. Khi họ cuối cùng thành công, họ sẽ có một cuộc sống xa hoa lâu dài.",
  10: "Số này khi đến như một cái tên biểu thị âm thanh hoặc sự cộng hưởng của lực nguyên thủy. Điều này được mô tả trong các văn bản cổ đại như một con rắn quấn quýt trong một bánh xe. Những người được đặt tên theo số này sẽ được tôn trọng và phổ biến. Sự tự tin và kiên nhẫn cùng tồn tại trong cuộc sống của họ nhưng vận may của họ sẽ thay đổi thường xuyên. Nó giống như một bánh xe quay, với những thăng trầm thường xuyên. Họ phải trung thực trong tất cả các hoạt động của họ và họ chắc chắn sẽ được nhiều người biết đến. Họ sẽ sống một cuộc sống hạnh phúc vì sẽ không thiếu tiền.",
  11: "Những người có số tên 11 sẽ vươn lên trong cuộc sống bằng niềm tin mạnh mẽ vào Chúa. Họ sẽ thu lợi bằng nhiều cách rất dễ dàng. Họ có thể bị đày đọa bởi những vấn đề và nguy hiểm không lường trước được, như thể để thử thách đức tin của họ. Đôi khi, họ có xu hướng can thiệp vào những vấn đề không liên quan đến họ. Họ có thể bị gia đình và bạn bè phản bội. Nếu họ có đức tin vào Chúa, họ chắc chắn sẽ đạt đến những đỉnh cao trong cuộc sống. Nếu họ thiếu đức tin, họ chắc chắn sẽ phải đối mặt với rất nhiều nguy hiểm.",
  12: "Những người này tự nhiên có khả năng thu hút mọi người bằng sức mạnh của lời nói. Họ hy sinh cuộc sống của mình vì phúc lợi và hạnh phúc của người khác bằng cách gánh vác gánh nặng của họ.",
  13: "Người dân ở các quận phía tây coi số này là không may mắn và điềm xấu. Họ không ở trong phòng hoặc nhà có số này và một số khách sạn thậm chí không có phòng có số này. Các sự kiện bất ngờ có tính chất đau buồn xảy ra thường xuyên. Những người đàn ông có số này có những trải nghiệm đắng cay và phải đối mặt với rất nhiều khó khăn vì phụ nữ. Mặc dù những người này quản lý để tiến triển trong cuộc sống vật chất, nhưng họ vẫn sẽ sống cuộc sống đầy đấu tranh. Đây không phải là một số tên mong muốn. Số này chỉ mang lại nỗi buồn nghiêm trọng, nếu số sinh và số vận mệnh cũng không may mắn.",
  14: "Số này phù hợp cho thương mại. Những người có số tên này luôn được bao quanh bởi rất nhiều người và đồ vật. Họ thành công trong các ngành nghề khác nhau và sẽ gặp nhiều bạn bè. Họ có thể gặp phải những vấn đề kỳ lạ và có thể đối mặt với những thất vọng khi tin tưởng người khác. Họ cũng có thể đối mặt với rủi ro từ sấm sét, nước và lửa. Họ thực hiện những chuyến đi thường xuyên. Những người này được khuyên nên cẩn thận khi đi du lịch trong các phương tiện di chuyển nhanh. Nếu sản phẩm mà họ buôn bán cũng thuộc số 14, nó sẽ có sự ủng hộ của công chúng tuyệt vời. Những vấn đề liên quan đến tình yêu và hôn nhân phải được xem xét và xem xét lại nhiều lần trước khi đưa ra quyết định. Nếu không, những người này có thể kết hôn vội vàng và hối hận khi rảnh rỗi. Số này có thể được gọi là một số rất may mắn.",
  15: "Quyết tâm thành công trong tất cả các kế hoạch và kiếm tiền và tìm kiếm để đạt được mục đích của một người được biểu thị bởi số này. Dục vọng, trả thù và ác ý có thể đẩy những người của số tên này đến một trạng thái tâm trí đê tiện. Họ có thể dần dần trở nên ích kỷ. Một vẻ ngoài quyến rũ và lời nói mạnh mẽ sẽ giúp họ đạt được lợi ích của mình. Mặc dù số tên này không phải là số thuận lợi để dẫn đến một cuộc sống đạo đức, nhưng nó là số lý tưởng cho sự thành công về vật chất thuần túy. Một nhân cách quyến rũ, sự xuất sắc trong nghệ thuật tinh tế và bản chất dí dỏm mang lại kết quả tích cực trong bất kỳ hoạt động nào có thể tạo ra lợi nhuận lớn. Nhiều người đến giúp họ khi cần. Cuộc sống sẽ xa hoa. Nếu số sinh của họ cũng thuận lợi, những người này sẽ đạt được danh tiếng, giàu có và sự khác biệt trong mọi khía cạnh của cuộc sống",
  16: "Số này biểu thị sự tiến bộ nhanh chóng và sự sụp đổ đột ngột. Các văn bản cổ đại mô tả số này bằng một bức tranh cho thấy sự tan vỡ của một tòa tháp cao và đầu của một vị vua với vương miện của ông rơi từ đỉnh của nó. Sự thật này đã được chứng minh khi Nhật Bản (16) rơi vào tay các quả bom hạt nhân. Hoàng đế Nhật Bản được coi là Thiên Chúa nhập thể và người dân của ông thậm chí sẽ không nhìn ông từ một nơi cao. Thật không may, người Mỹ đã ném bom Nhật Bản tước bỏ địa vị của Hoàng đế và những hậu quả là rõ ràng ngay cả ngày nay. Nếu số tên của bạn là 16, tốt hơn là bạn nên đổi sang một số may mắn khác. Số này gợi lên những suy nghĩ tưởng tượng mới sẽ được phản ánh trong các bài viết của người đó.",
  17: "Số tên này mang lại những phẩm chất ma quỷ trong khi theo đuổi các mục tiêu. Nó mang lại nhiều vấn đề và thử thách. Tuy nhiên, họ sẽ kiên trì đấu tranh không bỏ cuộc. Thất bại sẽ thúc đẩy họ đấu tranh tích cực hơn. Cuối cùng họ sẽ thành công, và họ đạt được sự thịnh vượng và danh tiếng lâu dài. Một số người trong số họ liều mạng để đạt được mục tiêu của họ và do đó đạt được tiến bộ. Thế giới không bao giờ có thể quên họ. Số này cũng có thể mang lại sức mạnh huyền bí.",
  18: "Số tên này, biểu thị sự suy giảm của thần thánh, sẽ mang lại những vấn đề, sự trì hoãn trong tất cả các vấn đề, sự quanh co và những kẻ thù nguy hiểm. Sự ích kỷ của họ có thể thúc đẩy họ tham gia vào các hoạt động chống xã hội. Họ đi theo những con đường xấu xa một cách có ý thức và trở nên rất ích kỷ. Cuộc sống thiếu hòa bình và nghỉ ngơi sẽ là thứ tự của ngày. Số này biểu thị sự phát triển của ham muốn cá nhân với cái giá của đức hạnh. Ham muốn sẽ kết thúc. Ân sủng thiêng liêng sẽ bị phá hủy. (Sử thi Hindu ghi lại rằng chiến tranh Mahabharat đã diễn ra trong 18 ngày và 18 sư đoàn đã chiến đấu trong cuộc chiến mà Pandavas phải giết chết những người lớn tuổi và các guru của họ trong trận chiến. Mặc dù được coi là thiêng liêng bởi người Hindu, đó là Bhagavat Gita gồm mười tám chương đã thúc đẩy Arjuna vào cuộc chiến). Số này, biểu thị sự ghen tị, ác ý và nguy hiểm do lửa và vũ khí, không được coi là đáng mong muốn.",
  19: "Các sách cổ về chủ đề này gán cho sự thông thạo ba thế giới cho Số này và do đó, những người này sẽ là tâm điểm chú ý ở bất cứ nơi nào họ đến. Số này biểu thị Mặt trời mọc. Điều này cũng đã được mô tả như \"Hoàng tử của Thế giới Thiên đường\" trong các văn bản Ấn Độ cổ đại và như một \"Người yêu lý tưởng\" trong kinh thánh Ai Cập. Mặt trời trở nên sáng hơn khi ngày dài ra và vì vậy những người này cũng tiến bộ khi tuổi tác của họ tiến triển. Vị trí, địa vị, hạnh phúc, thành công và sự giàu có sẽ dần dần gia tăng. Là người có kỷ luật tốt, họ sẽ trông trẻ và sẽ rất năng động ngay cả ở tuổi già của họ. Họ phải trung thực ngay cả trong những vấn đề liên quan đến khoái lạc giác quan.",
  20: "Số tinh thần này đại diện cho tiếng trống báo hiệu chiến thắng hoặc thắng lợi. Những người có số tên này làm việc để giải phóng và cải cách xã hội. Họ có khả năng cung cấp sự giảm nhẹ cho quần chúng từ nỗi buồn và đấu tranh. Thế giới sẽ ngưỡng mộ họ. Khi họ làm việc với động cơ cá nhân, họ cực kỳ ích kỷ và rất hủy diệt. Những người số 20 sẽ xuất sắc trong thực hành y tế sử dụng thuốc độc và xử lý thuốc độc. Những người này có khả năng đánh thức quần chúng đang ngủ và dẫn họ đến những thành tựu rất lớn. Khi họ đi ra ngoài để thỏa mãn nhu cầu ích kỷ của họ, sự chậm trễ và thất bại hoàn toàn sẽ sắp xảy ra. (HITLER, sinh vào ngày 20, đã thúc đẩy Đức vào cuộc chiến và phải đối mặt với thất bại nhục nhã. Ông là một ví dụ rất tốt về số tên này. Ông được đại diện bởi trống trận đã khích lệ người dân theo đuổi một động cơ ích kỷ dẫn đến sự hủy diệt)",
  21: "Những người này tự trung tâm và quan tâm đến hạnh phúc của riêng họ và những vấn đề có lợi cho họ. Với quyết tâm lớn, họ vươn lên đều đặn trong cuộc sống và đạt đến đỉnh cao của thành công. Hành vi khéo léo của họ giúp họ giải quyết tất cả các vấn đề của họ. Họ đấu tranh vất vả trong những ngày đầu nhưng đạt được thành công và hạnh phúc khi họ lớn lên. Họ sẽ đạt được và duy trì các vị trí tốt vĩnh viễn trong cuộc sống của họ.",
  22: "Các đặc điểm của những người sinh ngày 22 cũng đúng với số tên này. Số này kích động cảm xúc và cảm xúc cơ bản. Họ bị thu hút vào cờ bạc, uống rượu, đầu cơ và các tệ nạn khác và sẽ sẵn sàng tham gia vào chúng. Họ có thể hướng tới sự tự hủy hoại với tốc độ rất nhanh và thường được bao quanh bởi những người xấu xa và gian lận. Họ luôn có tiếng xấu. Họ không thích lời khuyên của người khác. Nếu ảnh hưởng của ngày sinh của họ thuận lợi, họ có thể thành công. Nếu không, họ phải đấu tranh để ngăn chặn thất bại hoàn toàn. Những người có động cơ ích kỷ luôn thúc đẩy những người này đến những cách thức quanh co để thúc đẩy lợi ích của riêng họ. Họ là những nhà quản lý giỏi và có thể đối mặt với bất kỳ vấn đề hoặc khó khăn nào với lòng can đảm. Các tình huống nguy hiểm được dự đoán trước. Họ thường đối mặt với sự sỉ nhục."
  // Add more descriptions as needed
};
